data_config_version = 0
uuid = "fb6b3653-b53d-4039-9a33-e92ca9f1d87b"
name = "juliaGameTheory"
plugins = ["store", "defaults", "memorise", "cache"]

[config.defaults.storage._]
checksum = "auto"

[[celegans-connectome-cook]]
uuid = "3390cb2b-6d63-4564-8841-af0330d26d1a"
description = "Cook 2019 C. elegans connectome"

    [[celegans-connectome-cook.storage]]
    driver = "web"
    checksum = "k12:33f530402e3f4ac495d8fafe8515269f"
    url = "https://github.com/openworm/ConnectomeToolbox/raw/05c50d5d197bdb7b1607c480a4f9e4aef9287232/cect/data/SI%205%20Connectome%20adjacency%20matrices.xlsx"

    [[celegans-connectome-cook.loader]]
    driver = "xlsx"
    range = "C3:QN303"
    sheet = "hermaphrodite chemical"

[[drosophilia-classification]]
uuid = "6a29ee7d-5b38-4199-83f0-4240698d9ac3"
description = "FlyWire Drosophilia cell classification"
 
    [[drosophilia-classification.storage]]
    driver = "filesystem"
    checksum = "md5:ab631fe049b8988aa99aaf9753997150"
    path = "data/external/classification.csv.gz"

    [[drosophilia-classification.loader]]
    driver = "chain"
    loaders = ["gzip", "csv"]

[[drosophilia-connectome]]
uuid = "9be3ad64-c2e1-4052-a4ac-1f6891e31be1"
description = "FlyWire Drosophilia connectome"
 
    [[drosophilia-connectome.storage]]
    driver = "filesystem"
    checksum = "md5:41206440318c77418bfc7cff1cb3e0fa"
    path = "data/external/connections.csv.gz"

    [[drosophilia-connectome.loader]]
    driver = "chain"
    loaders = ["gzip", "csv"]

[[drosophilia-connectome-web]]
uuid = "73af972c-b31b-4185-bbd9-30d85a32ecf9"
description = "FlyWire Drosophilia connectome"

    [[drosophilia-connectome-web.storage]]
    driver = "web"
    checksum = "md5:f48f972d262323a102aed49af1396b8a"
    url = "https://zenodo.org/records/10676866/files/proofread_connections_783.feather"

    [[drosophilia-connectome-web.loader]]
    driver = "arrow"
