name: Manuscript Compilation
on:
  push:
    tags:
      - '*.*.*' # semantic versioning
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile manuscript
        working-directory: papers/primary_manuscript
        run: |
          guix time-machine -C channels.scm -- shell --pure -m manifest.scm -- \
          latexmk Report.tex
      - name: Compile supplementary info
        working-directory: papers/primary_manuscript
        run: |
          guix time-machine -C channels.scm -- shell --pure -m manifest.scm -- \
          latexmk SupplementaryInformation.tex
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: papers/primary_manuscript/Report.pdf,papers/primary_manuscript/SupplementaryInformation.pdf
          artifactContentType: application/pdf
